Repository Midtrans/midtrans-go, pull requests merged in 2022-08, with the labels that each got.

#15 add QRString field to ChargeResponse
  coreapi/client_test.go
  coreapi/response.go
Labels: enhancement

#16 bump version v1.3.3
  coreapi/client_test.go
  midtrans.go
Labels: bug, enhancement

#18 add response on_us in charge response struct
  coreapi/response.go
Labels: enhancement

#19 update PaymentAccountResponse to correct api response structure
  coreapi/clienttokenization_test.go
  coreapi/response.go
Labels: bug

#20 Bump version and fix unit test related 8 bin update
  coreapi/client_test.go
  coreapi/clienttokenization_test.go
  midtrans.go
Labels: enhancement
